import type { AppPermission } from '../middleware/auth';

export type BusinessRoutePolicy = {
  router: 'inventory' | 'packages' | 'rates' | 'clients' | 'dashboard';
  method: 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  permission: AppPermission;
  audience: 'authenticated' | 'internal';
  resourceScope: string;
  effect: 'database' | 'provider' | 'cache' | 'job';
  conditionalPermission?: AppPermission;
};

// PS-421: deny-by-default inventory of business routes whose HTTP method can
// cause a DB, provider, cache, or durable-job side effect. Each route must
// delegate to one of these entries through requireBusinessRoutePolicy().
export const BUSINESS_ROUTE_POLICIES = {
  'inventory.ledger.delete': {
    router: 'inventory',
    method: 'DELETE',
    path: '/ledger/:ledgerId{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory-ledger:item-client-store',
    effect: 'database',
  },
  'inventory.catalog.create': {
    router: 'inventory',
    method: 'POST',
    path: '/',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:body-client',
    effect: 'database',
  },
  'inventory.catalog.patch': {
    router: 'inventory',
    method: 'PATCH',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.receive.one': {
    router: 'inventory',
    method: 'POST',
    path: '/:id{[0-9]+}/receive',
    permission: 'inventory:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.catalog.set-parent': {
    router: 'inventory',
    method: 'PUT',
    path: '/:id{[0-9]+}/set-parent',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.catalog.add-parent': {
    router: 'inventory',
    method: 'POST',
    path: '/:id{[0-9]+}/add-parent',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.catalog.remove-parent': {
    router: 'inventory',
    method: 'DELETE',
    path: '/:id{[0-9]+}/parents/:parentSkuId{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.adjust.one': {
    router: 'inventory',
    method: 'POST',
    path: '/:id{[0-9]+}/adjust',
    permission: 'inventory:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.receive.bulk': {
    router: 'inventory',
    method: 'POST',
    path: '/receive',
    permission: 'inventory:write',
    audience: 'internal',
    resourceScope: 'inventory:body-client-and-items',
    effect: 'database',
    conditionalPermission: 'settings:write',
  },
  'inventory.adjust.body': {
    router: 'inventory',
    method: 'POST',
    path: '/adjust',
    permission: 'inventory:write',
    audience: 'internal',
    resourceScope: 'inventory:item-client-store',
    effect: 'database',
  },
  'inventory.catalog.bulk-default-package': {
    router: 'inventory',
    method: 'POST',
    path: '/bulk-set-default-package',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:body-client-and-skus',
    effect: 'database',
  },
  'inventory.catalog.bulk-dimensions': {
    router: 'inventory',
    method: 'POST',
    path: '/bulk-update-dims',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:item-ids-client-store',
    effect: 'database',
  },
  'inventory.catalog.import-orders': {
    router: 'inventory',
    method: 'POST',
    path: '/import-from-orders',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:global-catalog',
    effect: 'database',
  },
  'inventory.catalog.sync-products': {
    router: 'inventory',
    method: 'POST',
    path: '/sync-products',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'inventory:global-catalog',
    effect: 'provider',
  },
  'packages.catalog.create': {
    router: 'packages',
    method: 'POST',
    path: '/',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:global-catalog',
    effect: 'database',
  },
  'packages.catalog.patch': {
    router: 'packages',
    method: 'PATCH',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
  },
  'packages.catalog.delete': {
    router: 'packages',
    method: 'DELETE',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
  },
  'packages.catalog.sync': {
    router: 'packages',
    method: 'POST',
    path: '/sync',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:global-catalog',
    effect: 'provider',
  },
  'packages.catalog.backfill-start-date': {
    router: 'packages',
    method: 'POST',
    path: '/backfill-start-date',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:global-catalog',
    effect: 'database',
  },
  'packages.receive': {
    router: 'packages',
    method: 'POST',
    path: '/:id{[0-9]+}/receive',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
    conditionalPermission: 'financials:write',
  },
  'packages.adjust': {
    router: 'packages',
    method: 'POST',
    path: '/:id{[0-9]+}/adjust',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
  },
  'packages.catalog.put': {
    router: 'packages',
    method: 'PUT',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
  },
  'packages.catalog.reorder-level': {
    router: 'packages',
    method: 'PATCH',
    path: '/:id{[0-9]+}/reorder-level',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:item-id',
    effect: 'database',
  },
  'packages.catalog.auto-create': {
    router: 'packages',
    method: 'POST',
    path: '/auto-create',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:global-catalog',
    effect: 'database',
  },
  'packages.catalog.import-dimensions': {
    router: 'packages',
    method: 'POST',
    path: '/import-standard-dimensions',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'packages:global-catalog',
    effect: 'database',
  },
  'rates.quote': {
    router: 'rates',
    method: 'POST',
    path: '/',
    permission: 'rates:quote',
    audience: 'authenticated',
    resourceScope: 'rates:client-store',
    effect: 'provider',
  },
  'rates.browse.workflow.start': {
    router: 'rates',
    method: 'POST',
    path: '/browse/workflow',
    permission: 'rates:quote',
    audience: 'authenticated',
    resourceScope: 'rates:order-or-client-store',
    effect: 'job',
  },
  'rates.shopify.quote': {
    router: 'rates',
    method: 'POST',
    path: '/shopify',
    permission: 'rates:quote',
    audience: 'internal',
    resourceScope: 'rates:order',
    effect: 'provider',
  },
  'rates.browse': {
    router: 'rates',
    method: 'POST',
    path: '/browse',
    permission: 'rates:quote',
    audience: 'authenticated',
    resourceScope: 'rates:order-or-client-store',
    effect: 'provider',
  },
  'rates.cache.bulk-read': {
    router: 'rates',
    method: 'POST',
    path: '/cached/bulk',
    permission: 'rates:quote',
    audience: 'authenticated',
    resourceScope: 'rates:each-order-or-client-store',
    effect: 'cache',
  },
  'rates.backfill.start': {
    router: 'rates',
    method: 'POST',
    path: '/backfill-best',
    permission: 'scope:global',
    audience: 'internal',
    resourceScope: 'rates:global',
    effect: 'job',
  },
  'rates.cache.delete': {
    router: 'rates',
    method: 'DELETE',
    path: '/cache',
    permission: 'scope:global',
    audience: 'internal',
    resourceScope: 'rates:global',
    effect: 'cache',
  },
  'rates.cache.clear-refetch': {
    router: 'rates',
    method: 'POST',
    path: '/cache-clear-and-refetch',
    permission: 'scope:global',
    audience: 'internal',
    resourceScope: 'rates:global',
    effect: 'cache',
  },
  'clients.catalog.create': {
    router: 'clients',
    method: 'POST',
    path: '/',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'clients:global-catalog',
    effect: 'database',
  },
  'clients.catalog.patch': {
    router: 'clients',
    method: 'PATCH',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'clients:item-client-store',
    effect: 'database',
  },
  'clients.catalog.delete': {
    router: 'clients',
    method: 'DELETE',
    path: '/:id{[0-9]+}',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'clients:item-client-store',
    effect: 'database',
  },
  'clients.orders.backfill': {
    router: 'clients',
    method: 'POST',
    path: '/:id{[0-9]+}/backfill-orders',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'clients:item-client-store',
    effect: 'database',
  },
  'clients.catalog.sync-stores': {
    router: 'clients',
    method: 'POST',
    path: '/sync-stores',
    permission: 'settings:write',
    audience: 'internal',
    resourceScope: 'clients:global-catalog',
    effect: 'provider',
  },
} as const satisfies Record<string, BusinessRoutePolicy>;

export type BusinessRoutePolicyId = keyof typeof BUSINESS_ROUTE_POLICIES;
