// PS-256 (durable runtime state) — RESTART-SAFE PRINT-QUEUE MERGED PDF.
//
// The merged batch-label PDF lives ONLY in process memory (MergeJob.mergedPdfBase64 in the
// in-memory mergeJobs Map). The durable MergeJobSnapshot persisted to the settings table is
// metadata-only (no bytes), so a server restart loses the PDF: the view/download/signed-url
// routes (which read getMergeJobStatus(jobId)) return 404 even though the snapshot still says
// status='done'. The operator loses the generated batch PDF.
//
// This is a durable side-store for the immutable merged PDF ARTIFACT only. We persist the
// already-generated bytes once the merge is done, and rehydrate them on an in-memory miss so the
// routes can still serve the batch after a restart. We never re-generate, re-fetch labels, buy
// postage, notify a marketplace, or mutate any shipped/cancelled order or shipment row.
//
// ENV-GATED, default OFF (DURABLE_PRINT_QUEUE_PDF). The OFF path is a TRUE no-op: persist is a
// no-op and get returns null with NO DB call, NO schema ensure, zero cost — so merging this
// changes nothing until DJ flips it on Render after a canary.
//
// Best-effort: persist/read NEVER throw into the merge or status hot path (mirrors the existing
// best-effort persistMergeJobSnapshot). Additive-table 500-safe pattern (like
// ensureWorkerStatusEventsSchema / ensureRateLimiterSchema): runtime CREATE TABLE IF NOT EXISTS,
// NOT in the drizzle schema index (a bare drizzle select() over the index would otherwise emit
// the new table and 500 prod before it exists). Bytes are stored as bytea (binary), not bloated
// base64 text, so a 1-5MB PDF stays compact.
import { sql as pg } from '../db/client.js';
import { env } from '../lib/env.js';

/** True only when DJ has flipped the canary on Render. Default OFF. */
export function durablePrintQueuePdfEnabled(): boolean {
  return env.DURABLE_PRINT_QUEUE_PDF;
}

let schemaEnsured: Promise<void> | null = null;

/** Memoized runtime DDL (mirrors ensureWorkerStatusEventsSchema). Additive, 500-safe. */
export async function ensurePrintQueuePdfSchema(): Promise<void> {
  schemaEnsured ??= (async () => {
    await pg`
      CREATE TABLE IF NOT EXISTS print_queue_merged_pdfs (
        job_id text PRIMARY KEY,
        file_name text,
        pdf_bytes bytea,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `;
    await pg`ALTER TABLE print_queue_merged_pdfs ENABLE ROW LEVEL SECURITY`;
  })().catch((err) => {
    schemaEnsured = null;
    throw err;
  });
  return schemaEnsured;
}

/**
 * Persist the immutable merged PDF for a done merge job. NO-OP when the flag is OFF (no DB, no
 * schema ensure). The PDF is immutable once done, so the UPSERT just keeps the latest bytes if
 * the same jobId is somehow persisted twice. Best-effort: never throws into the merge hot path —
 * a failed write is logged at most.
 */
export async function persistMergedPdf(
  jobId: string,
  fileName: string | null,
  base64: string,
): Promise<void> {
  if (!durablePrintQueuePdfEnabled()) return;
  if (!jobId || !base64) return;
  try {
    await ensurePrintQueuePdfSchema();
    // Store binary, not base64 text: decode to a Buffer so a 1-5MB PDF is ~33% smaller on disk.
    const bytes = Buffer.from(base64, 'base64');
    await pg`
      INSERT INTO print_queue_merged_pdfs (job_id, file_name, pdf_bytes, created_at)
      VALUES (${jobId}, ${fileName ?? null}, ${bytes}, now())
      ON CONFLICT (job_id) DO UPDATE
        SET file_name = ${fileName ?? null}, pdf_bytes = ${bytes}, created_at = now()
    `;
  } catch (err) {
    console.warn(
      '[print-queue-pdf-store] failed to persist merged PDF:',
      err instanceof Error ? err.message : err,
    );
  }
}

/**
 * Read the merged PDF bytes for a job and return them as a base64 string (the in-memory
 * MergeJob.mergedPdfBase64 shape). Returns null when the flag is OFF (no DB touched) or when no
 * row exists. Best-effort: never throws into the status/serve hot path.
 */
export async function getMergedPdfBase64(jobId: string): Promise<string | null> {
  if (!durablePrintQueuePdfEnabled()) return null;
  if (!jobId) return null;
  try {
    await ensurePrintQueuePdfSchema();
    const rows = await pg<{ pdfBytes: Buffer | null }[]>`
      SELECT pdf_bytes AS "pdfBytes"
      FROM print_queue_merged_pdfs
      WHERE job_id = ${jobId}
      LIMIT 1
    `;
    const bytes = rows[0]?.pdfBytes;
    if (!bytes) return null;
    // Encode the bytea Buffer back to base64 for the existing serve path.
    return Buffer.from(bytes).toString('base64');
  } catch (err) {
    console.warn(
      '[print-queue-pdf-store] failed to read merged PDF:',
      err instanceof Error ? err.message : err,
    );
    return null;
  }
}

/**
 * Delete merged-PDF rows older than maxAgeMs. NO-OP when the flag is OFF. Best-effort; never
 * throws. Retention is intentionally longer than the 30-min in-memory job retention so a download
 * survives a restart window (the caller passes a few hours).
 */
export async function cleanupOldMergedPdfs(maxAgeMs: number): Promise<void> {
  if (!durablePrintQueuePdfEnabled()) return;
  if (!(maxAgeMs > 0)) return;
  try {
    await ensurePrintQueuePdfSchema();
    const cutoff = new Date(Date.now() - maxAgeMs).toISOString();
    await pg`DELETE FROM print_queue_merged_pdfs WHERE created_at < ${cutoff}`;
  } catch (err) {
    console.warn(
      '[print-queue-pdf-store] failed to clean up old merged PDFs:',
      err instanceof Error ? err.message : err,
    );
  }
}
