import type { ConnectorCapability, ConnectorProvider } from './types.js';

export const connectorCapabilityMatrix: Record<ConnectorProvider, ConnectorCapability[]> = {
  shipstation: [
    'orders.import',
    'shipment.confirm',
    'rates.quote',
    'labels.create',
    'labels.void',
    'tracking.read',
    'products.import',
    'credentials.verify',
    'webhooks.receive',
  ],
  walmart: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'inventory.push',
    'products.import',
    'credentials.verify',
  ],
  walmart_shipping: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  shipp: ['rates.quote', 'labels.create', 'tracking.read', 'credentials.verify'],
  easypost: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify', 'webhooks.receive'],
  ups: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  fedex: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  usps: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  shipengine: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  ebay_shipping: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  amazon_shipping: ['rates.quote', 'labels.create', 'labels.void', 'tracking.read', 'credentials.verify'],
  ebay: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'products.import',
    'credentials.verify',
    'credentials.refresh',
    'webhooks.receive',
  ],
  shopify: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'inventory.push',
    'products.import',
    'credentials.verify',
    'credentials.refresh',
    'webhooks.receive',
  ],
  amazon: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'inventory.push',
    'products.import',
    'credentials.verify',
    'credentials.refresh',
  ],
  tiktok_shop: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'products.import',
    'credentials.verify',
    'credentials.refresh',
    'webhooks.receive',
  ],
  woocommerce: [
    'orders.import',
    'orders.statusSync',
    'shipment.confirm',
    'inventory.import',
    'products.import',
    'credentials.verify',
    'credentials.refresh',
    'webhooks.receive',
  ],
};
