#!/usr/bin/env tsx
/**
 * PS-502 — mutation matrix for the replacement contract guard.
 *
 * The guard is large and mostly green-by-construction, which is exactly the condition under
 * which a check quietly stops defending anything. Each mutation reintroduces a defect the
 * card names and requires the guard to go red AT THE CHECK THAT OWNS IT.
 *
 * DJ supplied `unlock shipped data` for PS-502 on 2026-08-19. These mutations exercise the
 * resulting static safety checks only: files are restored after every case, no command calls a
 * provider, and no shipment, inventory, billing or production row is touched.
 *
 * Run on a clean tree. Files are restored in a finally block.
 */
import { runMutationMatrix, type Mutation } from './lib/mutation-matrix';

const FINGERPRINT = 'src/services/replacement-source-line-fingerprint.ts';
const REFERENCE = 'src/services/replacement-reference.ts';
const STATE_MACHINE = 'src/services/replacement-state-machine.ts';
const ALLOWANCE = 'src/services/replacement-allowance.ts';
const BILLABILITY = 'src/services/replacement-billability.ts';
const CREATE = 'src/services/replacement-create-command.ts';
const SHIPMENT = 'src/services/replacement-shipment-command.ts';
const SCHEMA = 'src/db/schema/replacements.ts';
const BILLING_SCHEMA = 'src/db/schema/billing.ts';
const APPLIER = 'scripts/apply-ps-502-replacement-schema.ts';
const LIFECYCLE = 'src/services/replacement-lifecycle-command.ts';
const PURCHASE_REQ = 'src/services/replacement-purchase-request.ts';
const LABEL_BUY = 'src/services/replacement-label-purchase-command.ts';
const LABEL_VOID = 'src/services/replacement-label-void-command.ts';
const SHIPPED = 'src/services/replacement-shipped-command.ts';
const BILL_PLAN = 'src/services/replacement-billing-planner.ts';
const BILL_WRITE = 'src/services/replacement-billing-writer.ts';
const SWEEP = 'src/services/billing-outbound-sweep.ts';
const POLICY = 'src/services/billing-finalization-policy.ts';
const FOLD = 'src/services/billing-replacement-finalized-fold.ts';
const GENERATOR = 'src/services/billing.ts';
const NO_CHARGE = 'src/services/billing-cancelled-no-charge.ts';
const ROUTE = 'src/routes/replacements.ts';
const CHARGE_CANCEL = 'src/services/replacement-charge-cancellation.ts';
const DIAGNOSTICS = 'src/services/replacement-diagnostics.ts';
const MAIN = 'src/main.ts';
const SCHEMA_PROBE = 'src/services/replacement-schema-readiness.ts';
const INVOICE_TOTALS_OWNER = 'src/services/billing-invoice-totals.ts';
const MIGRATION_WORKFLOW = '.github/workflows/render-one-off-migration-ps502.yml';
const FENCE = 'src/services/replacement-customer-money.ts';
const MONEY_OWNER = 'src/services/customer-shipping-money.ts';
const PLANNER = 'src/services/replacement-billing-planner.ts';
const INVOICE_TOTALS = 'src/services/billing-invoice-totals.ts';
const HOLD = 'src/services/replacement-original-order-hold.ts';
const ORDER_LIFECYCLE = 'src/services/order-lifecycle-command.ts';
const UPSTREAM = 'src/services/fulfillment/upstream-reconcile.ts';
const ENV = 'src/lib/env.ts';
const PG17 = 'scripts/ps-502-replacement-concurrency-pg17.ts';
const FINANCIAL_ACTION = 'src/services/replacement-financial-action.ts';
const FINANCIAL_MIGRATION = 'drizzle/0103_ps502_replacement_financial_actions.sql';
const MONEY_SNAPSHOT = 'src/services/customer-shipping-money-snapshot.ts';
const PROVIDER_ADAPTER = 'src/services/replacement-label-provider.ts';
const CREDENTIAL_AUTHORITY = 'src/services/replacement-provider-credential-authority.ts';
const ANALYSIS = 'src/routes/analysis.ts';
const ADMIN = 'src/routes/admin.ts';
const LIFECYCLE_ORDER = 'src/services/order-lifecycle-command.ts';
const LABEL_BUY_OWNED = 'src/services/replacement-label-purchase-command.ts';
const OUTBOX = 'src/services/fulfillment/outbox.ts';
const LABELS = 'src/services/labels.ts';
const SYNC = 'src/services/shipment-sync.ts';
const SCHEDULER = 'src/services/sync-scheduler.ts';

const MUTATIONS: Mutation[] = [
  {
    id: 'M1',
    defect: 'quantity drops out of the fingerprint — the card\'s duplicate-SKU worst case reopens',
    file: FINGERPRINT,
    find: '    normalizeQuantity(facts.originalOrderedQuantity),',
    replace: '    null,',
    expect: 'DUPLICATE-SKU REORDER is caught (the card\'s worst case)',
  },
  {
    id: 'M2',
    defect: 'the format version leaves the tuple, so a layout change becomes indistinguishable from drift',
    file: FINGERPRINT,
    find: '    REPLACEMENT_FINGERPRINT_VERSION,',
    replace: '',
    expect: 'the format is versioned, so a layout change is deliberate not silent',
  },
  {
    id: 'M3',
    defect: 'delimiter-joined encoding replaces JSON, letting two lines forge one fingerprint',
    file: FINGERPRINT,
    find: /return JSON\.stringify\(\[([\s\S]*?)\]\);/,
    replace: "return [$1].join('|');",
    expect: 'a separator inside a field cannot forge another line\'s fingerprint',
  },
  {
    id: 'M4',
    defect: 'SKU comparison becomes case-sensitive, so a case change reads as product drift',
    file: FINGERPRINT,
    find: "  return typeof value === 'string' ? value.trim().toLowerCase() : '';",
    replace: "  return typeof value === 'string' ? value.trim() : '';",
    expect: 'SKU case and surrounding space are not drift',
  },
  {
    id: 'M5',
    defect: 'numeric quantity is no longer canonicalised, so "2.000" and 2 diverge',
    file: FINGERPRINT,
    find: "  const parsed = typeof value === 'number' ? value : Number(String(value).trim());",
    replace: '  const parsed = value as number;',
    expect: 'numeric quantity representations are one value ("2" = 2 = "2.000")',
  },
  {
    id: 'M6',
    defect: 'review is shown only the first other home of the frozen SKU',
    file: FINGERPRINT,
    find: '    .sort((a, b) => a - b);',
    replace: '    .slice(0, 1).sort((a, b) => a - b);',
    expect: 'review can tell "this line moved" from "this product is gone"',
  },
  {
    id: 'M7',
    defect: 'the first replacement is emitted as -1, creating a second spelling of one identity',
    file: REFERENCE,
    find: '  return sequence === 1',
    replace: '  return false',
    expect: 'the first replacement is the BARE form, never -1',
  },
  {
    id: 'M8',
    defect: 'allocation counts references instead of taking max, so a cancelled gap is reused',
    file: REFERENCE,
    find: '    if (parsed.sequence > highest) highest = parsed.sequence;',
    replace: '    highest += 1;',
    expect: 'a GAP is never reused (a cancelled replacement keeps its reference)',
  },
  {
    id: 'M9',
    defect: 'the parser accepts the non-canonical -1 spelling',
    file: REFERENCE,
    find: '  if (sequence < 2) return null;',
    replace: '  if (sequence < 0) return null;',
    expect: '"1321-REPLACE-1" is rejected as a reference',
  },
  {
    id: 'M10',
    defect: 'another order\'s references advance this order\'s sequence',
    file: REFERENCE,
    find: '    if (!parsed || parsed.orderNumber !== trimmed) continue;',
    replace: '    if (!parsed) continue;',
    expect: 'another order\'s references do not advance this order',
  },
  {
    id: 'M11',
    defect: 'label_failed -> shipped becomes legal — goods ship with no label',
    file: STATE_MACHINE,
    find: "  label_failed: ['review', 'approved', 'label_created', 'cancelled'],",
    replace: "  label_failed: ['review', 'approved', 'label_created', 'cancelled', 'shipped'],",
    expect: 'label_failed -> shipped is ILLEGAL',
  },
  {
    id: 'M12',
    defect: 'a never-shipped status consumes allowance, so a cancelled request reduces the cap',
    file: ALLOWANCE,
    find: "const ALLOWANCE_CONSUMING_STATUSES: readonly ReplacementStatus[] = ['shipped', 'completed'];",
    replace: "const ALLOWANCE_CONSUMING_STATUSES: readonly ReplacementStatus[] = ['shipped', 'completed', 'approved'];",
    expect: 'approved does NOT consume allowance',
  },
  {
    id: 'M13',
    defect: 'a post-ship review stops consuming, so the same units can go out twice',
    file: ALLOWANCE,
    find: "  return row.status === 'review' && row.shippedAt != null;",
    replace: '  return false;',
    expect: 'a POST-ship review DOES consume (it shipped, then drifted)',
  },
  {
    id: 'M14',
    defect: 'the cap stops aggregating on the frozen coordinate, so a reorder resets it',
    file: ALLOWANCE,
    find: '    if (row.sourceLineFingerprint !== input.sourceLineFingerprint) continue;',
    replace: '    if (false) continue;',
    expect: 'the cap aggregates on the FROZEN coordinate, not on whatever sits there now',
  },
  {
    id: 'M15',
    defect: 'an over-ship override no longer needs a reason — an unattributable claim',
    file: ALLOWANCE,
    find: "  if (override?.hasOverridePermission && reason !== '') {",
    replace: '  if (override?.hasOverridePermission) {',
    expect: 'an override requires a reason, not just the permission',
  },
  {
    id: 'M16',
    defect: 'operator liability stops forcing non-billable — the client is charged for our mistake',
    file: BILLABILITY,
    find: "  return owner === 'operator' ? false : null;",
    replace: '  return null;',
    expect: 'operator liability FORCES non-billable, even for finance',
  },
  {
    id: 'M17',
    defect: 'billability stays editable past label_created, after postage is committed',
    file: BILLABILITY,
    find: '  if (!BILLABILITY_EDITABLE_STATUSES.includes(change.status)) {',
    replace: '  if (false) {',
    expect: 'billability is FROZEN from label_created onward',
  },
  {
    id: 'M18',
    defect: 'one permission suffices, so replacements:billing alone can move money',
    file: BILLABILITY,
    find: '    || !hasPermission(change.actor, FINANCIALS_WRITE_PERMISSION)',
    replace: '',
    expect: 'replacements:billing alone is not enough — financials:write is also required',
  },
  {
    id: 'M19',
    defect: 'a migration column is dropped from Drizzle, making it invisible to every typed query',
    file: SCHEMA,
    find: "    sourceLineFingerprint: text('source_line_fingerprint').notNull(),",
    replace: '',
    expect: 'replacement_items: every migration column is declared in Drizzle',
  },
  {
    id: 'M20',
    defect: 'Drizzle declares a column the database lacks — a bare select() then 500s the route',
    file: SCHEMA,
    find: '    quantity: integer().notNull(),',
    replace: "    quantity: integer().notNull(),\n    phantomColumn: text('phantom_column'),",
    expect: 'replacement_items: Drizzle declares NO column the migration lacks',
  },
  {
    id: 'M21',
    defect: 'the schema stops mirroring 0097\'s ON DELETE, disagreeing with the deployed database',
    file: BILLING_SCHEMA,
    // Regex, not a literal: billing.ts is tracked with CRLF (core.autocrlf=true), so a
    // literal "\n" here matches nothing and the mutation silently goes stale.
    find: /replacementId: integer\('replacement_id'\)\.references\(\(\) => replacements\.id, \{\r?\n(\s*)onDelete: 'restrict',/,
    replace: "replacementId: integer('replacement_id').references(() => replacements.id, {\n$1onDelete: 'set null',",
    expect: 'both replacement financial FKs are ON DELETE RESTRICT',
  },
  {
    id: 'M22',
    defect: 'the order-scoped lock is dropped — two concurrent creates both read the same allowance',
    file: CREATE,
    find: /await tx\.execute\(sql`select pg_advisory_xact_lock[^`]*`\);/,
    replace: '',
    expect: 'a create after durable cancellation/refund evidence is refused under the order lock',
  },
  {
    id: 'M23',
    defect: 'the lock class collides with billing\'s client lock',
    file: CREATE,
    find: 'const REPLACEMENT_ORDER_LOCK_CLASS = 36423;',
    replace: 'const REPLACEMENT_ORDER_LOCK_CLASS = 36421;',
    expect: 'the lock class is distinct from billing\'s',
  },
  {
    id: 'M24',
    defect: 'a retried create errors instead of returning the replacement it already made',
    file: CREATE,
    find: '      return { replacement: existing, created: false };',
    replace: "      throw new ReplacementCreateError('REPLACEMENT_NO_ITEMS', 'duplicate', 409);",
    expect: 'a matching repeated key returns the EXISTING replacement rather than erroring',
  },
  {
    id: 'M25',
    defect: 'the cumulative cap is no longer consulted before creating',
    file: CREATE,
    find: '      const verdict = evaluateReplacementAllowance({',
    replace: '      const verdict = { allowed: true, viaOverride: false } as any; const skipped = ({',
    expect: 'the allowance is evaluated BEFORE the insert',
  },
  {
    id: 'M26',
    defect: 'billability authority is no longer consulted, so an operator can set it',
    file: CREATE,
    find: '    const billability = evaluateBillabilityChange({',
    replace: '    const billability = { allowed: true, billable: false } as any; const skippedB = ({',
    expect: 'billability is evaluated BEFORE the insert',
  },
  {
    id: 'M27',
    defect: 'the reference is string-built, filing the SECOND replacement under the first\'s identity',
    file: CREATE,
    find: '    const reference = nextReplacementReference(',
    replace: '    const reference = `${order.orderNumber}-REPLACE`; const unusedRef = (',
    expect: 'the reference is ALLOCATED, never string-built',
  },
  {
    id: 'M28',
    defect: 'create starts writing a shipment row, so a rejected request has already moved goods',
    file: CREATE,
    find: '    await tx.insert(replacementItems).values(',
    replace: '    await tx.insert(shipments).values({} as any);\n    await tx.insert(replacementItems).values(',
    expect: 'create writes NO shipments row',
  },
  {
    id: 'M29',
    defect: 'drift is no longer re-resolved before a shipment exists',
    file: SHIPMENT,
    find: '    const finding = await findFrozenLineDrift(tx, replacement);',
    replace: '    const finding = null as unknown as null;',
    expect: 'drift is re-resolved BEFORE the shipment is inserted',
  },
  {
    id: 'M30',
    defect: 'the drift review throws instead of committing — the operator sees 409 forever and nothing is recorded',
    file: SHIPMENT,
    find: '      return { drifted: true, orderLineIndex: item.orderLineIndex, reference: replacement.reference };',
    replace: "      throw new ReplacementShipmentError(REPLACEMENT_ERROR_CODES.SOURCE_LINE_CHANGED, 'drift', 409);",
    expect: 'a drift review is COMMITTED, then reported',
  },
  {
    id: 'M31',
    defect: 'the state_version guard is dropped, so the two-transaction gap goes unchecked',
    file: SHIPMENT,
    find: '        eq(replacements.stateVersion, before.stateVersion),',
    replace: '',
    expect: 'the link is guarded by status AND state_version',
  },
  {
    id: 'M32',
    defect: 'a retry mints a SECOND shipment for one replacement',
    file: SHIPMENT,
    find: '  if (outcome.existingShipmentId != null) {',
    replace: '  if (false) {',
    expect: 'an already-attached replacement returns its existing shipment',
  },
  {
    id: 'M33',
    defect: 'the replacement shipment claims the original order number — reads as a duplicate label',
    file: SHIPMENT,
    find: '        orderNumber: before.reference,',
    replace: '        orderNumber: String(before.orderId),',
    expect: 'the shipment carries the REPLACEMENT reference, not the original order number',
  },
  {
    id: 'M34',
    defect: 'the outbound re-ship is flagged as a return, inverting its direction in every report',
    file: SHIPMENT,
    find: "        source: 'replacement',",
    replace: "        source: 'replacement',\n        isReturn: true,",
    expect: 'a replacement is outbound — isReturn is never set',
  },
  // ── Hermes correctness findings, at 07f8a9bb ────────────────────────────────
  {
    id: 'M35',
    defect: 'quantity is truncated again — 1.9 silently becomes 1 and one unit ships',
    file: CREATE,
    find: '    if (!Number.isInteger(item.quantity) || item.quantity <= 0) {',
    replace: '    if (false) {',
    expect: 'a fractional or non-positive quantity is a coded 400, not a database CHECK error',
  },
  {
    id: 'M36',
    defect: 'duplicate line coordinates reach the unique index instead of a coded 400',
    file: CREATE,
    find: '    if (seenIndexes.has(item.orderLineIndex)) {',
    replace: '    if (false) {',
    expect: 'duplicate line coordinates are rejected before the transaction',
  },
  {
    id: 'M37',
    defect: 'an arbitrary reason is accepted against the frozen vocabulary',
    file: CREATE,
    find: '  if (!REPLACEMENT_REASONS.includes(input.reason as ReplacementReason)) {',
    replace: '  if (false) {',
    expect: 'the frozen reason vocabulary is enforced server-side',
  },
  {
    id: 'M38',
    defect: 'the whole-request signature stops being compared — a reused key returns the WRONG replacement',
    file: CREATE,
    find: '      if (existing.requestSignature !== requestSignature) {',
    replace: '      if (false) {',
    expect: 'idempotency binds the WHOLE request, not just its items',
  },
  {
    id: 'M39',
    defect: 'the billability reason is validated and then discarded again',
    file: CREATE,
    find: "        eventType: 'replacement_billability_set',",
    replace: "        eventType: 'replacement_requested_again',",
    expect: 'the billability reason is RECORDED, not just validated',
  },
  {
    id: 'M40',
    // RE-TARGETED (PS-502 item 11). The drift review's predicate moved out of the shipment
    // command and into enterReplacementReview, so the defect is reintroduced THERE. Its owner
    // is now the per-site check, and that is the point of the pair: M47 kills applyTransition's
    // copy of this line and M40 kills the review writer's. A file-wide presence check would
    // catch M47 and MISS M40 — so the two together are what prove that check walks every
    // update site rather than settling for one match somewhere in the file.
    defect: 'the shared review writer drops its expected-status predicate',
    file: LIFECYCLE,
    // Anchored on the row-count check below it, which makes the block unique to the review
    // writer: applyTransition's copy of the same predicate is followed by moved.length, not by
    // reviewed.length, so this block cannot match it.
    find: /      eq\(replacements\.status, before\.status\),\n      eq\(replacements\.stateVersion, before\.stateVersion\),\n    \)\)\n    \.returning\(\);\n\n  if \(reviewed\.length === 0\) \{/,
    replace: "      eq(replacements.stateVersion, before.stateVersion),\n    ))\n    .returning();\n\n  if (reviewed.length === 0) {",
    expect: 'EVERY update to replacements is guarded on status AND state_version',
  },
  {
    id: 'M41',
    // RE-TARGETED (PS-502 item 11): the row-count check moved into the shared writer with the
    // update it guards. The name reviewed appears nowhere else in the lifecycle file, so the two-space
    // form targets enterReplacementReview and nothing else.
    defect: 'a lost drift race still appends an event describing a transition that never happened',
    file: LIFECYCLE,
    find: '  if (reviewed.length === 0) {',
    replace: '  if (false) {',
    expect: 'a lost drift race appends NO event',
  },
  {
    id: 'M42',
    defect: 'an authorized client-liability FALSE loses its reason again',
    file: CREATE,
    find: "    if (input.liabilityOwner === 'client') {",
    replace: '    if (billability.billable) {',
    expect: 'an authorized client-liability decision is recorded whether TRUE or FALSE',
  },
  {
    id: 'M43',
    defect: 'a behaviourally significant field drops out of the request signature',
    file: CREATE,
    find: '    billabilityReason: normalizeReason(input.billabilityReason),',
    replace: '',
    expect: 'the signature covers every behaviourally significant field',
  },
  {
    id: 'M44',
    defect: 'the production migration lane goes stale again — a migration the code needs is not deployed',
    file: APPLIER,
    find: "const SQL_0099 = 'drizzle/0099_ps502_replacement_request_signature.sql';",
    replace: '',
    expect: 'the runner applies 0099_ps502_replacement_request_signature.sql',
  },  {
    id: 'M45',
    defect: 'the concurrency lane drops to a single backend and proves nothing',
    file: PG17,
    find: 'max: 8, prepare: false',
    replace: 'max: 1, prepare: false',
    expect: 'the pool opens MULTIPLE backends',
  },  {
    id: 'M46',
    defect: 'a transition stops checking its row count and records a move that never happened',
    file: LIFECYCLE,
    find: '  if (moved.length === 0) {',
    replace: '  if (false) {',
    expect: 'a zero-row transition is a coded 409 and appends NO event',
  },
  {
    id: 'M47',
    defect: 'the expected-status predicate is dropped from every transition',
    file: LIFECYCLE,
    find: '      eq(replacements.status, before.status),',
    replace: '',
    expect: 'EVERY update to replacements is guarded on status AND state_version',
  },
  {
    id: 'M48',
    defect: 'a remap no longer needs the override capability',
    file: LIFECYCLE,
    find: '  if (!input.actor.permissions.includes(REPLACEMENT_OVERRIDE_PERMISSION)) {',
    replace: '  if (false) {',
    expect: 'a remap requires the dedicated override capability and a reason',
  },
  {
    id: 'M49',
    defect: 'a remap stops re-running the allowance against its new coordinate',
    file: LIFECYCLE,
    find: '    const verdict = evaluateReplacementAllowance({',
    replace: '    const verdict = { allowed: true } as any; const skipped = ({',
    expect: 'a remap re-runs the allowance against the NEW coordinate',
  },  {
    id: 'M50',
    defect: 'a policy default is accepted while its DJ decision is still unfrozen',
    file: PURCHASE_REQ,
    find: '    if (!FROZEN_DECISIONS[decision.key]) {',
    replace: '    if (false) {',
    expect: 'a POLICY DEFAULT for address is refused while its decision is unfrozen',
  },
  {
    id: 'M51',
    defect: 'a decision is frozen in code rather than by DJ on the card',
    file: PURCHASE_REQ,
    find: '  address: false,',
    replace: '  address: true,',
    expect: 'every DJ decision governing a default is still UNFROZEN',
  },
  {
    id: 'M52',
    defect: 'an override no longer needs an actor and a reason',
    file: PURCHASE_REQ,
    find: '  if (!chosenBy || !reason) {',
    replace: '  if (false) {',
    expect: 'an override of address without an ACTOR is refused',
  },
  {
    id: 'M53',
    defect: 'internal cost data is allowed to travel in a provider request',
    file: PURCHASE_REQ,
    find: '    if (FORBIDDEN_COST_KEYS.includes(key)) {',
    replace: '    if (false) {',
    expect: 'internal cost data cannot travel in a provider request',
  },
  {
    id: 'M54',
    defect: 'the package fingerprint stops covering weight, so a retry can buy a different parcel',
    file: PURCHASE_REQ,
    find: '      request.package.packageId, request.package.weightOz,',
    replace: '      request.package.packageId,',
    expect: 'the fingerprint covers the values a purchase depends on',
  },  {
    id: 'M55',
    defect: 'the label feature flag defaults ON',
    file: ENV,
    find: '  REPLACEMENTS_LABEL_ENABLED: booleanFlag(false),',
    replace: '  REPLACEMENTS_LABEL_ENABLED: booleanFlag(true),',
    expect: 'both replacement feature flags remain DEFAULT OFF',
  },
  {
    id: 'M56',
    defect: 'the durable intent is written AFTER dispatch, so a crash leaves no proof',
    file: LABEL_BUY,
    find: '    const [intent] = await tx.insert(replacementLabelPurchaseIntents).values({',
    replace: '    const [intent] = await tx.insert(replacements).values({',
    expect: 'the durable intent is committed BEFORE dispatch',
  },
  {
    id: 'M57',
    defect: 'an unresolved intent no longer blocks a further dispatch',
    file: LABEL_BUY,
    find: '    if (unresolved) {',
    replace: '    if (false) {',
    expect: 'an unresolved intent BLOCKS a further dispatch',
  },
  {
    id: 'M58',
    defect: 'drift after dispatch discards the purchased label instead of reviewing',
    file: LABEL_BUY,
    find: /(reviewReason: 'original_order_line_drift',\s*\n\s*)eventType: 'replacement_label_purchased_into_review',/,
    replace: "$1eventType: 'replacement_label_discarded',",
    expect: 'post-dispatch drift PRESERVES the label and reviews',
  },  {
    id: 'M59',
    defect: 'an unconfirmed void is recorded as voided while the label is still live',
    file: LABEL_VOID,
    find: '  if (!result.voided) {',
    replace: '    if (false) {',
    expect: 'an UNCONFIRMED void is never recorded as voided',
  },
  {
    id: 'M60',
    defect: 'a repeated void sends a second destructive call',
    file: LABEL_VOID,
    find: "    if (intent.voidState === 'voided') {",
    replace: '    if (false) {',
    expect: 'an already-voided label sends no second destructive call',
  },
  {
    id: 'M61',
    defect: 'the void capability check is removed',
    file: LABEL_VOID,
    find: '  if (!input.actor.permissions.includes(REPLACEMENT_LABEL_PERMISSION)) {',
    replace: '  if (false) {',
    expect: 'ALL THREE provider-reaching void/reconcile commands require the label capability and a reason',
  },  {
    id: 'M62',
    defect: 'the inventory kill switch stops blocking, so stock moves with no ledger entry',
    file: SHIPPED,
    find: '    if (env.INVENTORY_AUTO_DEDUCT !== true) {',
    replace: '    if (false) {',
    expect: 'the inventory kill switch is checked BEFORE any write',
  },
  {
    id: 'M63',
    defect: 'the ledger key drops the replacement item, collapsing duplicate-SKU lines',
    file: SHIPPED,
    find: '    `:item:${input.replacementItemId}:inventory:${input.inventoryId}:ship`;',
    replace: '    `:inventory:${input.inventoryId}:ship`;',
    expect: 'inventory identity is replacement- and ITEM-scoped',
  },
  {
    id: 'M64',
    defect: 'a billable replacement can ship with no billing lines',
    file: SHIPPED,
    find: '    if (replacement.billable) {',
    replace: '    if (false) {',
    expect: 'a billable replacement CANNOT ship without billing lines',
  },
  {
    id: 'M65',
    defect: 'an unresolved package is silently skipped',
    file: SHIPPED,
    find: '    if (!input.consumePackage) {',
    replace: '    if (false) {',
    expect: 'an unresolved package blocks shipping rather than being skipped',
  },
  {
    id: 'M66',
    defect: 'a second command starts writing status shipped',
    file: LIFECYCLE,
    find: "      to: 'approved',",
    replace: "      to: 'shipped' as never,",
    expect: 'the lifecycle command never writes `shipped`',
  },  {
    id: 'M67',
    defect: 'a non-billable replacement writes a $0.00 line instead of none',
    file: BILL_PLAN,
    find: '  if (!facts.billable) return [];',
    replace: '  if (false) return [];',
    expect: 'billable=false produces NO line, not a zero line',
  },
  {
    id: 'M68',
    defect: 'a missing frozen money tuple is treated as zero rather than refused',
    file: BILL_PLAN,
    find: '  if (!customerPostage || !Number.isFinite(customerPostage.amount)) {',
    replace: '  if (false) {',
    expect: 'a missing frozen money tuple FAILS CLOSED',
  },
  {
    id: 'M69',
    defect: 'the writer stops counting the RETURNED rows, so a partial insert reads as complete',
    file: BILL_WRITE,
    find: '  if (inserted.length !== planned.length) {',
    replace: '  if (false) {',
    expect: 'the writer inserts with RETURNING and counts the RETURNED rows',
  },
  {
    id: 'M70',
    defect: 'onConflictDoNothing is added to a money path',
    file: BILL_WRITE,
    find: '  ).returning({ id: billingLineItems.id, lineType: billingLineItems.lineType });',
    replace: '  ).onConflictDoNothing().returning({ id: billingLineItems.id, lineType: billingLineItems.lineType });',
    expect: 'there is NO onConflictDoNothing on a money path',
  },
  {
    id: 'M71',
    defect: 'the cross-table invariant stops being asserted before the insert',
    file: BILL_WRITE,
    find: '    assertReplacementLineInvariants(line, {',
    replace: '    void ({',
    expect: 'cross-table invariants are asserted in the service',
  },  {
    id: 'M72',
    defect: 'the sweep stops preserving replacement lines, so a routine rebuild erases them',
    file: SWEEP,
    find: '  ...REPLACEMENT_LINE_TYPES,',
    replace: '',
    expect: 'the outbound sweep PRESERVES replacement line types',
  },
  {
    id: 'M73',
    defect: 'regeneration stops excluding invoiced rows and deletes finalized money',
    file: BILL_WRITE,
    find: '      eq(billingLineItems.invoiced, false),',
    replace: '',
    expect: 'the regeneration delete carries ALL FOUR scoping terms',
  },  {
    id: 'M74',
    defect: 'the credit stops carrying replacement_id, so one of two cannot be attributed',
    file: POLICY,
    find: /(adjustmentKind: 'credit',\s*\n)        replacementId: input\.replacementId,/,
    replace: '$1        replacementId: null,',
    expect: 'the credit CARRIES replacement_id through the projection',
  },
  {
    id: 'M75',
    defect: 'the reconciler credits the whole frozen total, refunding twice on a retry',
    file: POLICY,
    find: 'const outstandingCents = frozenCents + priorCents;',
    replace: 'const outstandingCents = frozenCents;',
    expect: 'it credits the DELTA, not the frozen total',
  },
  {
    id: 'M76',
    defect: 'cancellation stops excluding invoiced lines and deletes finalized money',
    file: BILL_WRITE,
    find: /(cancelReplacementBillingInTransaction[\s\S]*?)      eq\(billingLineItems\.invoiced, false\),\r?\n/,
    replace: '$1',
    expect: 'cancellation removes ONLY editable replacement-scoped lines',
  },  {
    id: 'M77',
    defect: 'frozen discovery goes back to a column constraint 0074 forbids, so it matches nothing',
    file: POLICY,
    find: '      where line.client_id = ${input.clientId}',
    replace: '      where line.client_id = ${input.clientId} and line.source_finalization_id is not null',
    expect: 'discovery never asks for source_finalization_id',
  },
  {
    id: 'M78',
    defect: 'the fold stops scoping to frozen money and folds open-period charges too',
    file: FOLD,
    find: '        and line.invoiced = true',
    replace: '',
    expect: 'the finalized fold counts ONLY money frozen in THIS window',
  },
  {
    id: 'M79',
    defect: 'the generator stops folding, so regeneration credits the replacement away again',
    file: GENERATOR,
    find: '  await foldFinalizedReplacementTotalsIntoCandidates(',
    replace: '  await Promise.resolve(); void foldFinalizedReplacementTotalsIntoCandidates; if (false) await foldFinalizedReplacementTotalsIntoCandidatesUnused(',
    expect: 'the generator folds replacement money BEFORE reconciling',
  },
  {
    id: 'M80',
    defect: 'the SQL twin drops the replacement types while the TypeScript set keeps them',
    file: NO_CHARGE,
    find: /\n      'replace_postage', 'replace_pick_pack'/,
    replace: '',
    expect: 'a cancelled original does not zero replacement money — both twins',
  },  {
    id: 'M81',
    defect: 'AC-16 reuses the drift review reason, so the queue cannot tell the two apart',
    file: HOLD,
    find: "      reviewReason: 'original_order_cancelled_label_live',",
    replace: "      reviewReason: 'original_order_line_drift',",
    expect: 'AC-16 keeps its OWN review reasons, never the drift code',
  },
  {
    id: 'M82',
    defect: 'the sweep drops the order lock and can interleave with an in-flight ship',
    file: HOLD,
    find: '  await tx.execute(sql`select pg_advisory_xact_lock(36423, ${input.orderId})`);',
    replace: '',
    expect: 'the sweep takes the SAME order lock every replacement command takes',
  },
  {
    id: 'M83',
    defect: 'the open-hold check narrows to the idempotency key, aborting the second signal',
    file: HOLD,
    find: /sql`\(\$\{replacementOriginalOrderHolds\.resolvedAt\} is null\n[^`]*`,\n/,
    replace: '',
    expect: 'an open hold blocks re-classification, as the partial index requires',
  },
  {
    id: 'M84',
    defect: 'the local cancel branch stops fanning out to its replacements',
    file: ORDER_LIFECYCLE,
    find: '    await raiseReplacementOriginalOrderHoldsInTransaction(tx, {',
    replace: '    if (false) await raiseReplacementOriginalOrderHoldsInTransaction(tx, {',
    expect: 'the local cancel branch fans out IN THE SAME TRANSACTION',
  },
  {
    id: 'M85',
    defect: 'the upstream producer stops looking for shipped originals, so AC-16 never fires',
    file: UPSTREAM,
    find: "    && candidate.orderStatus === 'shipped'",
    replace: "    && candidate.orderStatus === 'awaiting_shipment'",
    expect: 'the upstream producer raises holds WITHOUT moving the order',
  },
  // ── PS-502 item 11 — the three hand-rolled review writers routed through one ──────────────
  //
  // Deduplicating a write creates a NEW way to regress: someone re-inlines a copy. That is not
  // hypothetical here — it is exactly what the label-purchase path had already done, matching on
  // id alone with no predicate and no row-count check. Each of these puts a hand-rolled copy
  // back at one call site and requires that site's delegation check to be the first to go red.
  {
    id: 'M86',
    defect: 'the shipment command hand-rolls its drift review again, on id alone',
    file: SHIPMENT,
    find: '      await enterReplacementReview(tx, replacement, {',
    replace: "      await tx.update(replacements).set({ status: 'review' })\n        .where(eq(replacements.id, replacement.id));\n      await inlinedReview({",
    expect: 'the drift review delegates to the ONE guarded review writer',
  },
  {
    id: 'M87',
    defect: 'the label-purchase command hand-rolls its post-dispatch review again, on id alone',
    file: LABEL_BUY,
    find: '    await enterReplacementReview(tx, before.replacement, {',
    replace: "    await tx.update(replacements).set({ status: 'review' })\n      .where(eq(replacements.id, before.replacement.id));\n    await inlinedReview({",
    expect: 'the post-dispatch review delegates to the ONE guarded review writer',
  },
  {
    id: 'M88',
    // Global regex: the hold classifies three phases and calls the writer at all three, so
    // replacing one leaves two and the check would stay green on a defect that is present.
    defect: 'AC-16 stops using the shared review writer, so the copies can drift apart again',
    file: HOLD,
    find: /enterReplacementReview\(tx, before, \{/g,
    replace: "tx.update(replacements).set({ status: 'review' })\n      .where(eq(replacements.id, before.id)); await inlinedReview({",
    expect: 'there is ONE shared review writer, and AC-16 uses it',
  },  {
    id: 'M89',
    defect: 'the fence returns the carrier cost, billing raw postage as customer money',
    file: FENCE,
    find: '    amount: frozen.cShippingRateAmount,',
    replace: '    amount: frozen.selectedRateCost,',
    expect: 'the fence returns the CUSTOMER amount, never the carrier cost',
  },
  {
    id: 'M90',
    defect: 'the fence stops reading the frozen tuple and accepts whatever it was handed',
    file: FENCE,
    find: '  if (!frozen) return null;',
    replace: '  if (!frozen) return { amount: 0, policyVersion: CUSTOMER_SHIPPING_MONEY_POLICY_VERSION, source: \'frozen_customer_shipping_money\' };',
    expect: 'the fence accepts only a tuple with customer-money PROVENANCE',
  },
  {
    id: 'M91',
    defect: 'the invoice owner loses a replacement bucket, so that money belongs to nothing',
    file: INVOICE_TOTALS,
    find: /^.*line_type = 'replace_pick_pack'.*$\r?\n/m,
    replace: '',
    expect: 'both replacement line types have a bucket in EVERY summary owner',
  },  {
    id: 'M92',
    defect: 'the router is mounted but drops out of the auth allowlist, shipping unauthenticated',
    file: MAIN,
    find: /\n  \/\/ PS-502: mounting a router does NOT[\s\S]*?\n  '\/replacements',/,
    replace: '',
    expect: 'the router is in protectedPrefixes, not merely mounted',
  },
  {
    id: 'M93',
    defect: 'the disabled surface stops naming itself, so it reads as a plain permission denial',
    file: ROUTE,
    find: "      { error: 'The replacements surface is not enabled', code: 'REPLACEMENTS_DISABLED' },",
    replace: "      { error: 'The replacements surface is not enabled' },",
    expect: 'the WHOLE router is gated, with a code distinct from not-found',
  },
  {
    id: 'M94',
    defect: 'a route drops to requirePermission, admitting a client portal session',
    file: ROUTE,
    find: "app.get('/', requireInternalPermission('replacements:read')",
    replace: "app.get('/', requirePermission('replacements:read')",
    expect: 'every route denies portal roles outright',
  },
  {
    id: 'M95',
    defect: 'the mapper swallows an unrecognised failure as a coded refusal',
    file: ROUTE,
    find: "  if (typeof e?.httpStatus !== 'number' || typeof e?.code !== 'string') throw error;",
    replace: "  if (false) throw error;",
    expect: 'the route never decides the status code',
  },  {
    id: 'M96',
    defect: 'zero-count classes are reported, burying the real ones in a list of noise',
    file: DIAGNOSTICS,
    find: '    if (count === 0) continue;',
    replace: '',
    expect: 'classes with nothing wrong are OMITTED, and healthy is explicit',
  },
  {
    id: 'M97',
    defect: 'the unbilled sweep stops checking billable, so correct behaviour is reported as an anomaly',
    file: DIAGNOSTICS,
    find: '      where r.billable = true',
    replace: '      where true',
    expect: 'the unbilled-shipment query is scoped to BILLABLE replacements',
  },
  {
    id: 'M98',
    defect: 'an anomaly loses the guidance that makes it actionable',
    file: DIAGNOSTICS,
    find: /\n    action:\n      'Do NOT hand-write a billing line[\s\S]*?fix that path\.',/,
    replace: "\n    action: '',",
    expect: 'every anomaly carries what it means and what to do',
  },  {
    id: 'M99',
    defect: 'the cancel fan-out loses its schema probe, so cancelling an order needs a table production lacks',
    file: ORDER_LIFECYCLE,
    find: '    if (await replacementSchemaPresent(tx)) {',
    replace: '    if (true) {',
    expect: 'every PRE-EXISTING path probes only the replacement dependency it reads',
  },
  {
    id: 'M100',
    defect: 'a migration drops out of the ARCHIVE while its digest stays in the verification prose',
    file: MIGRATION_WORKFLOW,
    find: /\n            drizzle\/0101_ps502_replacement_original_order_holds\.sql/,
    replace: '',
    expect: 'the workflow SHIPS and pins 0101_ps502_replacement_original_order_holds.sql',
  },
  {
    id: 'M101',
    defect: 'a digest argument is dropped, so the runner never verifies that migration',
    file: MIGRATION_WORKFLOW,
    find: ' --digest101=${d101}',
    replace: '',
    expect: 'the workflow SHIPS and pins 0101_ps502_replacement_original_order_holds.sql',
  },
  {
    id: 'M102',
    defect: 'the probe serves an explicit connection from the memo, letting a test answer for production',
    file: SCHEMA_PROBE,
    find: '  if (conn) return probe(conn);',
    replace: '',
    expect: 'an explicit connection is never served from the memo',
  },  {
    id: 'M103',
    defect: 'the deduction goes back to the caller\'s array, so an extra line moves unfrozen stock',
    file: SHIPPED,
    find: '    for (const item of items) {\n      const stock = validatedInventoryByItem.get(item.id)!;',
    replace: '    for (const line of input.inventoryLines) { const item = items[0]!;\n      const stock = validatedInventoryByItem.get(item.id)!;',
    expect: 'the deduction iterates the FROZEN items, not the caller\'s lines',
  },
  {
    id: 'M104',
    defect: 'the duplicate-mapping check goes, so one item can be deducted twice',
    file: SHIPPED,
    find: '      if (mappingByItem.has(line.replacementItemId)) {',
    replace: '      if (false) {',
    expect: 'one mapping per frozen item, and only this replacement\'s items',
  },
  {
    id: 'M105',
    defect: 'the quantity is taken from the caller again',
    file: SHIPPED,
    find: '        qty: -item.quantity,',
    replace: '        qty: -Math.abs(Math.trunc((line as { qty?: number }).qty ?? 1)),',
    expect: 'the quantity comes from the frozen row',
  },  {
    id: 'M106',
    defect: 'the fold drops its period bound and folds money frozen on a different invoice',
    file: FOLD,
    find: /\n        and closed\.period_start < \$\{period\.dateTo\}::timestamptz\n        and closed\.period_end > \$\{period\.dateFrom\}::timestamptz/,
    replace: '',
    expect: 'the finalized fold counts ONLY money frozen in THIS window',
  },
  {
    id: 'M107',
    defect: 'a line joining two overlapping closed periods is counted twice',
    file: FOLD,
    find: '      select distinct',
    replace: '      select',
    expect: 'one line is counted once even if two closed periods overlap',
  },  {
    id: 'M108',
    defect: 'the probe remembers a NEGATIVE, so a migrated database looks unmigrated until restart',
    file: SCHEMA_PROBE,
    find: '      if (!found) present = null;',
    replace: '',
    expect: 'a NEGATIVE answer is never remembered',
  },
  {
    id: 'M109',
    defect: 'the canonical invoice totals assume replacement_id exists again',
    file: INVOICE_TOTALS_OWNER,
    find: '  const replacementCountSql = (await billingLineItemsHasReplacementIdColumn(conn))',
    replace: '  const replacementCountSql = (true)',
    expect: 'the canonical invoice totals probe on the CALLER\'s connection',
  },  {
    id: 'M110',
    defect: 'recovery goes back to resolving the intent and never records the label',
    file: LABEL_VOID,
    find: '      const recorded = await recordPurchasedReplacementLabelInTransaction(tx, {',
    replace: '      const recorded = await Promise.resolve(null as never); if (false) await recordPurchasedReplacementLabelInTransactionUnused({',
    expect: 'BOTH callers use it — the purchase and the recovery',
  },
  {
    id: 'M111',
    defect: 'the recorder stops re-checking drift that appeared while the purchase was in flight',
    file: LABEL_BUY,
    find: '  const drift = await findFrozenLineDrift(tx, before.replacement);',
    replace: '  const drift = null;',
    expect: 'it does every part of what the label MEANS',
  },  {
    id: 'M112',
    defect: 'cancelling a replacement stops cancelling its charge, leaving money for a called-off re-ship',
    file: LIFECYCLE,
    find: '    await completePreShipCancellationCleanupInTransaction(tx, {',
    replace: '    if (false) await completePreShipCancellationCleanupInTransaction(tx, {',
    expect: 'pre-ship cancellation cleans its charge BEFORE the lifecycle move in ONE transaction',
  },
  {
    id: 'M113',
    defect: 'resolving a review into cancelled skips the money, so the door taken changes the outcome',
    file: LIFECYCLE,
    find: /(if \(input\.to === 'cancelled'\) \{[\s\S]{0,220})      await completePreShipCancellationCleanupInTransaction\(tx, \{/,
    replace: '$1      if (false) await completePreShipCancellationCleanupInTransaction(tx, {',
    expect: 'resolving a review INTO cancelled uses the SAME atomic cleanup boundary',
  },
  {
    id: 'M114',
    defect: 'the early return swallows every case, so a credit is never raised at all',
    file: CHARGE_CANCEL,
    find: '  if (removal.invoicedRetained === 0) {',
    replace: '  if (removal.invoicedRetained >= 0) {',
    expect: 'the compatibility owner removes editable lines, then settles invoiced ones AFTER the commit',
  },  {
    id: 'M115',
    defect: 'the purchase stops freezing customer money, so the fence has nothing to accept again',
    file: LABEL_BUY,
    find: '      freezeReplacementCustomerShippingMoney(input.shipmentId, sp));',
    replace: '      Promise.resolve(null as never));',
    expect: 'the purchase freezes customer money in the same commit as the label',
  },
  {
    id: 'M116',
    defect: 'the replacement freeze admits return shipments, relaxing a return-only fence',
    file: MONEY_OWNER,
    find: '      eq(shipments.isReturn, false),',
    replace: '',
    expect: 'a replacement has its OWN freeze, not the return one relaxed',
  },  {
    id: 'M117',
    defect: 'the canonical credit-note writer assumes replacement_id exists, breaking every credit on a pre-0097 database',
    file: POLICY,
    find: '  const withReplacementId = await billingCreditNotesHasReplacementIdColumn(conn);',
    replace: '  const withReplacementId = true;',
    expect: 'the credit CARRIES replacement_id through the projection',
  },
  {
    id: 'M118',
    defect: 'the replacement fence falls back to the generic historical snapshot reader',
    file: FENCE,
    find: '  const frozen = readFrozenReplacementCustomerShippingMoney(input.frozenCustomerShippingMoney);',
    replace: '  const frozen = readFrozenCustomerShippingMoney(input.frozenCustomerShippingMoney);',
    expect: 'the fence accepts only a tuple with customer-money PROVENANCE',
  },
  {
    id: 'M119',
    defect: 'the replacement reader accepts a tuple with no exact pricing-authority receipt',
    file: MONEY_SNAPSHOT,
    find: '    !frozen.customerShippingPricingAuthority',
    replace: '    false',
    expect: 'the replacement-specific reader requires exact active pricing authority',
  },
  {
    id: 'M120',
    defect: 'the replacement freeze escapes its receipt transaction to re-read cached policy',
    file: MONEY_OWNER,
    find: '  const decision = await decideCustomerShippingMoneyForRow(row, { exec });',
    replace: '  const decision = await decideCustomerShippingMoneyForRow(row);',
    expect: 'the replacement freeze records exact pricing authority from the receipt transaction',
  },
  {
    id: 'M121',
    defect: 'Phase 3 drops the intent-derived order lock before locking the intent row',
    file: LABEL_BUY,
    find: /  await tx\.execute\(sql`\r?\n    select pg_advisory_xact_lock\([^`]*join replacements r on r\.id = i\.replacement_id[^`]*`\);\r?\n/,
    replace: '',
    expect: 'intent-derived order locking precedes the intent row lock and every receipt mutation',
  },
  {
    id: 'M122',
    defect: 'the intent chain stops proving that the shipment source is replacement-owned',
    file: LABEL_BUY,
    find: "    && shipment.source === 'replacement';",
    replace: '    && true;',
    expect: 'the intent, replacement and shipment must form one replacement-owned chain',
  },
  {
    id: 'M123',
    defect: 'a purchased recorder replay writes the receipt and event again',
    file: LABEL_BUY,
    find: "  if (before.intent.state === 'purchased') {",
    replace: '  if (false) {',
    expect: 'a purchased replay returns the complete durable receipt without another write or event',
  },
  {
    id: 'M124',
    defect: 'the recorder can claim an intent after it has left the unresolved states',
    file: LABEL_BUY,
    find: /(eq\(replacementLabelPurchaseIntents\.replacementShipmentId, input\.shipmentId\),\r?\n)      sql`\$\{replacementLabelPurchaseIntents\.state\} in \('provider_pending', 'reconcile_required'\)`,/,
    replace: '$1      sql`true`,',
    expect: 'the recorder claims only unresolved intents and a stale loser returns the purchased winner',
  },
  {
    id: 'M125',
    defect: 'provider-confirmed recovery pre-mutates the intent before the shared recorder',
    file: LABEL_VOID,
    find: '      const recorded = await recordPurchasedReplacementLabelInTransaction(tx, {',
    replace: '      await tx.update(replacementLabelPurchaseIntents).set({ state: \'purchased\' });\n      const recorded = await recordPurchasedReplacementLabelInTransaction(tx, {',
    expect: 'provider-confirmed recovery delegates directly to the recorder in ONE transaction',
  },
  {
    id: 'M126',
    defect: 'purchase drops the shared replacements:label capability check before money can move',
    file: LABEL_BUY,
    find: '  if (!input.actor.permissions?.includes(REPLACEMENT_LABEL_PERMISSION)) {',
    replace: '  if (false) {',
    expect: 'the gate runs BEFORE any transaction or provider access',
  },
  {
    id: 'M127',
    defect: 'finalized billing waits for unrelated hold tables instead of probing only replacement_id',
    file: FOLD,
    find: '  if (!(await billingLineItemsHasReplacementIdColumn(conn))) {',
    replace: '  if (!(await replacementSchemaPresent(conn))) {',
    expect: 'every PRE-EXISTING path probes only the replacement dependency it reads',
  },
  {
    id: 'M128',
    defect: 'the main replacement surface defaults ON despite the requested dark deployment',
    file: ENV,
    find: '  REPLACEMENTS_ENABLED: booleanFlag(false),',
    replace: '  REPLACEMENTS_ENABLED: booleanFlag(true),',
    expect: 'both replacement feature flags remain DEFAULT OFF',
  },
  {
    id: 'M129',
    defect: 'AC-16 trusts lifecycle text instead of authoritative shipped_at dispatch evidence',
    file: HOLD,
    find: '  if (before.shippedAt != null) {',
    replace: "  if (before.status === 'shipped' || before.status === 'completed') {",
    expect: 'shipped_at is authoritative even when lifecycle text disagrees',
  },
  {
    id: 'M130',
    defect: 'AC-16 ignores editable billing and auto-cancels an undispatched replacement with money',
    file: HOLD,
    find: '    .where(eq(billingLineItems.replacementId, before.id))',
    replace: '    .where(and(eq(billingLineItems.replacementId, before.id), eq(billingLineItems.invoiced, true)))',
    expect: 'ANY replacement billing row blocks automatic cancellation',
  },
  {
    id: 'M131',
    defect: 'a clean automatic cancellation leaves an open operator hold with no question',
    file: HOLD,
    find: "outcome.disposition === 'no_action' || outcome.disposition === 'cancelled'",
    replace: "outcome.disposition === 'no_action'",
    expect: 'a clean pre-dispatch cancel closes its hold in the same transaction',
  },
  {
    id: 'M132',
    defect: 'post-ship reversal accepts replacements:billing without financials:write',
    file: FINANCIAL_ACTION,
    find: '[REPLACEMENT_BILLING_PERMISSION, FINANCIALS_WRITE_PERMISSION]',
    replace: '[REPLACEMENT_BILLING_PERMISSION]',
    expect: 'financial reversal requires BOTH permissions before schema or database access',
  },
  {
    id: 'M133',
    defect: 'the route attempts cleanup before committing the durable financial obligation',
    file: ROUTE,
    find: '        const requested = await deps.requestFinancialReversal({',
    replace: '        await deps.processFinancialAction(-1);\n        const requested = await deps.requestFinancialReversal({',
    expect: 'the route commits the durable obligation before best-effort processing',
  },
  {
    id: 'M134',
    defect: 'a reused financial idempotency key is accepted without matching the full decision',
    file: FINANCIAL_ACTION,
    find: '      assertReplayMatches(existing as ReplacementFinancialActionRow, expected);',
    replace: '      void existing; void expected;',
    expect: 'the post-ship decision requires written reason + stable key and replays by full signature',
  },
  {
    id: 'M135',
    defect: 'the financial action starts rewriting replacement lifecycle status',
    file: FINANCIAL_ACTION,
    find: '    const removal = await conn.transaction(async (tx) => {',
    replace: '    await conn.transaction(async (tx) => tx.update(replacements).set({ status: \'cancelled\' }));\n    const removal = await conn.transaction(async (tx) => {',
    expect: 'financial reversal preserves lifecycle and touches no provider, stock, package or marketplace',
  },
  {
    id: 'M136',
    defect: 'the durable worker loses SKIP LOCKED and can double-claim concurrent work',
    file: FINANCIAL_ACTION,
    find: '        for update skip locked',
    replace: '        for update',
    expect: 'the durable worker claims with a lease and SKIP LOCKED',
  },
  {
    id: 'M137',
    defect: 'the worker removes editable lines from a sibling replacement',
    file: FINANCIAL_ACTION,
    find: /(const removed = await cancelReplacementBillingInTransaction\(tx, \{\r?\n)        replacementId: action\.replacement_id,/,
    replace: '$1        replacementId: action.replacement_id + 1,',
    expect: 'the worker removes and credits ONLY the action replacement on the supplied database',
  },
  {
    id: 'M138',
    defect: 'a repeated worker appends the financial-completion event again',
    file: FINANCIAL_ACTION,
    find: '        .onConflictDoNothing({ target: replacementActivityEvents.idempotencyKey });',
    replace: ';',
    expect: 'completion is append-only and replay-safe',
  },
  {
    id: 'M139',
    defect: 'the repair scanner starts enqueuing dispatched cancelled replacements',
    file: FINANCIAL_ACTION,
    find: '        and replacement.shipped_at is null',
    replace: '',
    expect: 'the repair scanner targets only stranded pre-ship cancelled replacement money',
  },
  {
    id: 'M140',
    defect: '0103 leaves the financial-action ledger exposed through the public Data API',
    file: FINANCIAL_MIGRATION,
    find: 'alter table replacement_financial_actions enable row level security;',
    replace: '',
    expect: '0103 exposes no public Data-API write surface',
  },
  {
    id: 'M141',
    defect: '0103 allows completed actions without a completion timestamp',
    file: FINANCIAL_MIGRATION,
    find: "    check ((status = 'completed') = (completed_at is not null))",
    replace: '    check (true)',
    expect: '0103 is an append-only retry authority with strict identity and completion shape',
  },
  {
    id: 'M142',
    defect: 'Drizzle omits 0103 credited_amount, making the durable result invisible',
    file: SCHEMA,
    find: "    creditedAmount: numeric('credited_amount', { precision: 12, scale: 2 }).notNull().default('0'),",
    replace: '',
    expect: 'replacement_financial_actions: every migration column is declared in Drizzle',
  },
  {
    id: 'M143',
    defect: '0103 drops out of the Render archive while its digest prose remains',
    file: MIGRATION_WORKFLOW,
    find: /\r?\n            drizzle\/0103_ps502_replacement_financial_actions\.sql/,
    replace: '',
    expect: 'the workflow SHIPS and pins 0103_ps502_replacement_financial_actions.sql',
  },
  {
    id: 'M144',
    defect: 'the Render job stops supplying the mandatory 0103 digest',
    file: MIGRATION_WORKFLOW,
    find: ' --digest103=${d103}',
    replace: '',
    expect: 'the workflow SHIPS and pins 0103_ps502_replacement_financial_actions.sql',
  },
  {
    id: 'M145',
    defect: '0103 is read and pinned but no longer applied inside the one transaction',
    file: APPLIER,
    find: '      for (const migration of pendingMigrations) {',
    replace: '      for (const migration of pendingMigrations.filter((m) => m.stage !== 8)) {',
    expect: 'the migrations apply in ONE transaction',
  },
  {
    id: 'M146',
    defect: 'the operator read-back stops verifying the 0103 client foreign key',
    file: APPLIER,
    find: "      ['clients', 'replacement_financial_actions_client_id_fkey'],",
    replace: "      ['clients', 'replacement_financial_actions_client_id_fkey_unchecked'],",
    expect: 'the runner reads back 0103 columns, indexes, constraints, FKs and RLS',
  },
  {
    id: 'M147',
    defect: '0103 readiness serves an injected connection from the production memo',
    file: FINANCIAL_ACTION,
    find: '  if (conn !== db) return probeFinancialActionSchema(conn);',
    replace: '',
    expect: '0103 readiness is positive-only and explicit connections are never memoized',
  },
  {
    id: 'M148',
    defect: 'the finalized replacement credit escapes the worker\'s supplied database',
    file: FINANCIAL_ACTION,
    find: '      }, conn, async () => undefined)',
    replace: '      })',
    expect: 'the worker removes and credits ONLY the action replacement on the supplied database',
  },
  {
    id: 'M149',
    defect: '0102 reporting totals drop out of the archive even though PS-502 reads them',
    file: MIGRATION_WORKFLOW,
    find: /\r?\n            drizzle\/0102_billing_summary_metrics_replacement_totals\.sql/,
    replace: '',
    expect: 'the workflow SHIPS and pins 0102_billing_summary_metrics_replacement_totals.sql',
  },
  {
    id: 'M150',
    defect: 'the Render job stops supplying the mandatory 0102 digest',
    file: MIGRATION_WORKFLOW,
    find: ' --digest102=${d102}',
    replace: '',
    expect: 'the workflow SHIPS and pins 0102_billing_summary_metrics_replacement_totals.sql',
  },
  {
    id: 'M151',
    defect: 'lifecycle dispatch text without shipped_at is mislabeled as a live-label review',
    file: HOLD,
    find: "      reviewReason: 'original_order_cancelled_dispatch_inconsistent',",
    replace: "      reviewReason: 'original_order_cancelled_label_live',",
    expect: 'lifecycle dispatch text without shipped_at enters its dedicated review',
  },
  {
    id: 'M152',
    defect: 'the financial endpoint loses its replacements:billing exposure gate',
    file: ROUTE,
    find: "    requireInternalPermission('replacements:billing'),",
    replace: '',
    expect: 'AC-13 is a strict, scoped financial-reversal route — never lifecycle cancellation',
  },
  {
    id: 'M153',
    defect: 'the financial endpoint substitutes financials:write for its replacements:billing exposure gate',
    file: ROUTE,
    find: "    requireInternalPermission('replacements:billing'),",
    replace: "    requireInternalPermission('financials:write'),",
    expect: 'AC-13 is a strict, scoped financial-reversal route — never lifecycle cancellation',
  },
  {
    id: 'M154',
    defect: 'label purchase reaches validation and the handler without the separate label feature refusal',
    file: ROUTE,
    find: /(    requireInternalPermission\('replacements:label'\),\r?\n)    requireLabelFeature,(\r?\n    zValidator\('json', purchaseLabelBody\),)/,
    replace: '$1$2',
    expect: 'every label purchase/retry/recovery/void route stays behind label RBAC and the DEFAULT-OFF label flag',
  },
  {
    id: 'M155',
    defect: 'label purchase loads tenant data without its narrow RBAC refusal',
    file: ROUTE,
    find: /    requireInternalPermission\('replacements:label'\),\r?\n(    requireLabelFeature,\r?\n    zValidator\('json', purchaseLabelBody\),)/,
    replace: '$1',
    expect: 'every label purchase/retry/recovery/void route stays behind label RBAC and the DEFAULT-OFF label flag',
  },
  {
    id: 'M156',
    defect: 'shipping mutates inventory without inventory:write at the request boundary',
    file: ROUTE,
    find: /    requireInternalPermission\('inventory:write'\),\r?\n(    requireLabelFeature,\r?\n    zValidator\('json', shipBody\),)/,
    replace: '$1',
    expect: 'ship requires replacement + inventory capabilities and the label feature gate',
  },
  {
    id: 'M157',
    defect: 'purchase chooses a provider before the replacement is tenant-scoped',
    file: ROUTE,
    find: /(    '\/:id\{\[0-9\]\+\}\/label\/purchase',[\s\S]*?    async \(c\) => \{\r?\n)(      const replacement = await deps\.loadScopedReplacement\(c, Number\(c\.req\.param\('id'\)\)\);)/,
    replace: "$1      deps.providerFor(Number(c.req.param('id')));\n$2",
    expect: 'every side-effect route resolves tenant scope before its command or provider factory',
  },
  {
    id: 'M158',
    defect: 'the router-level replacement flag is registered after side-effect handlers',
    file: ROUTE,
    find: "app.use('*', async (c, next) => {",
    replace: "app.route('/', createReplacementSideEffectRouter());\napp.use('*', async (c, next) => {",
    expect: 'all pre-handler refusals run before scope loading, provider selection or commands',
  },
  {
    id: 'M159',
    defect: 'void_pending and void_reconcile_required are treated as permission to call the destructive provider again',
    file: LABEL_VOID,
    find: '    if (intent.voidState != null) {',
    replace: '    if (false) {',
    expect: 'an unresolved void attempt is a hard stop before a second destructive call',
  },
  {
    id: 'M160',
    defect: 'constructing the route provider starts a database read before any request gate runs',
    file: PROVIDER_ADAPTER,
    find: /(\): ReplacementLabelProvider & ReplacementLabelVoidProvider \{\r?\n)(  return \{)/,
    replace: '$1  void loadReplacementProviderContext(replacementId);\n$2',
    expect: 'constructing the replacement provider is lazy and performs no I/O',
  },
  {
    id: 'M161',
    defect: 'a direct or store-scoped synthetic account reaches replacement postage without authoritative recovery',
    file: PROVIDER_ADAPTER,
    find: '      if (directLabelAccountRefFromProviderId(request.carrier.providerAccountId)) {',
    replace: '      if (false && directLabelAccountRefFromProviderId(request.carrier.providerAccountId)) {',
    expect: 'direct, store-scoped and ambiguous account paths fail closed before postage',
  },
  {
    id: 'M162',
    defect: 'two matching ShipStation accounts are accepted as one unambiguous authority',
    file: PROVIDER_ADAPTER,
    find: '  if (matchingCarriers.length !== 1) {',
    replace: '  if (matchingCarriers.length === 0) {',
    expect: 'direct, store-scoped and ambiguous account paths fail closed before postage',
  },
  {
    id: 'M163',
    defect: 'provider recovery looks up an idempotency key without scoping it to the replacement',
    file: PROVIDER_ADAPTER,
    find: /(async function findIntentForLookup[\s\S]*?\.where\(and\(\r?\n)      eq\(replacementLabelPurchaseIntents\.replacementId, replacementId\),\r?\n/,
    replace: '$1',
    expect: 'purchase recovery reloads one scoped frozen intent and the current exact credential',
  },
  {
    id: 'M164',
    defect: 'provider void accepts a caller key that does not match the purchased intent',
    file: PROVIDER_ADAPTER,
    find: 'input.idempotencyKey !== replacementVoidIdempotencyKey(intent)',
    replace: 'false',
    expect: 'void reloads one purchased intent, its frozen request and its exact owning credential',
  },
  {
    id: 'M165',
    defect: 'replacement purchase sends the original order id as provider shipment identity',
    file: PROVIDER_ADAPTER,
    find: '      ssOrderId: null,',
    replace: '      ssOrderId: context.orderId,',
    expect: 'the adapter writes no local lifecycle and carries no original-order marketplace identity',
  },
  {
    id: 'M166',
    defect: 'the migration certification lane stops proving the separately running API/worker SHA',
    file: MIGRATION_WORKFLOW,
    find: /\r?\n          npm run test:ps-502-runtime-version/,
    replace: '',
    expect: 'API and persisted worker identities are separate and certified in both PS-502 lanes',
  },
  {
    id: 'M167',
    defect: 'provider recovery reuses no current ShipStation credential/account authority before lookup',
    file: PROVIDER_ADAPTER,
    find: /(async function lookupShipStationPurchase[\s\S]*?try \{\r?\n)    authority = await resolveShipStationAccountAuthority\(context, request\);/,
    replace: '$1    authority = {} as ShipStationAccountAuthority;',
    expect: 'purchase recovery reloads one scoped frozen intent and the current exact credential',
  },
  {
    id: 'M168',
    defect: 'the flags-off scheduler still scans historical replacements for new cleanup work',
    file: SCHEDULER,
    find: '      const replacementCleanupRecovered = env.REPLACEMENTS_ENABLED',
    replace: '      const replacementCleanupRecovered = true',
    expect: 'the DEFAULT-OFF replacement flag blocks historical replacement discovery',
  },
  {
    id: 'M169',
    defect: 'the scheduler strands already-authorized durable money when the HTTP feature rolls back',
    file: SCHEDULER,
    find: '        replacementFinancials = await processReplacementFinancialActionsOnce({ limit: 5 });',
    replace: '        replacementFinancials = env.REPLACEMENTS_ENABLED\n          ? await processReplacementFinancialActionsOnce({ limit: 5 })\n          : { schemaReady: false, processed: 0, succeeded: 0, failed: 0 };',
    expect: 'already-authorized durable financial obligations drain even while flags are off',
  },
  {
    id: 'M170',
    defect: 'a retry sees its committed credit but reports zero credits and zero amount on the action',
    file: POLICY,
    find: /        adjustedCount \+= 1;\r?\n        creditedCents \+= moneyCents\(existingActionCredit\.amount\);/,
    replace: '        void existingActionCredit.amount;',
    expect: 'a retry recovers its already-committed credit into the durable action result',
  },
  {
    id: 'M171',
    defect: 'AC-16 treats a confirmed-void purchased intent as live postage because lifecycle still says label_created',
    file: HOLD,
    find: /      sql`\(\$\{replacementLabelPurchaseIntents\.voidState\} is null or \$\{replacementLabelPurchaseIntents\.voidState\} <> 'voided'\)`,/,
    replace: '      sql`true`,',
    expect: 'a purchased but CONFIRMED-VOID intent is no longer a live label',
  },
  {
    id: 'M172',
    defect: 'shipping blocks only confirmed voids and treats pending, reconciliation and unknown states as active labels',
    file: SHIPPED,
    find: '      && intent.voidState === null',
    replace: "      && intent.voidState !== 'voided'",
    expect: 'ONLY an explicit active/null void state can ship',
  },
  {
    id: 'M173',
    defect: 'a caller-selected inactive inventory row can be deducted',
    file: SHIPPED,
    find: '          eq(inventory.active, true),',
    replace: '',
    expect: 'inventory ids stay candidates until remapped SKU, client and active authority all agree',
  },
  {
    id: 'M174',
    defect: 'a caller-selected inventory row belonging to another client can be deducted',
    file: SHIPPED,
    find: '          eq(inventory.clientId, Number(replacement.clientId)),',
    replace: '',
    expect: 'inventory ids stay candidates until remapped SKU, client and active authority all agree',
  },
  {
    id: 'M175',
    defect: 'a caller-selected inventory row for the wrong SKU can be deducted',
    file: SHIPPED,
    find: '          sql`lower(btrim(${inventory.sku})) = lower(btrim(${expectedSku}))`,',
    replace: '',
    expect: 'inventory ids stay candidates until remapped SKU, client and active authority all agree',
  },
  {
    id: 'M176',
    defect: 'inventory validation ignores the latest audited remap and compares the stale requested line',
    file: SHIPPED,
    find: '      const effectiveLineIndex = latestRemap?.resolvedOrderLineIndex ?? item.orderLineIndex;',
    replace: '      const effectiveLineIndex = item.orderLineIndex;',
    expect: 'inventory ids stay candidates until remapped SKU, client and active authority all agree',
  },
  {
    id: 'M177',
    defect: 'the ship HTTP body lets the caller supply a display name beside the inventory candidate',
    file: ROUTE,
    find: '    inventoryId: z.coerce.number().int().positive(),',
    replace: "    inventoryId: z.coerce.number().int().positive(),\n    name: z.string().optional(),",
    expect: 'ship accepts inventory candidates only, never caller display or quantity data',
  },
  {
    id: 'M178',
    defect: 'a provisional ShipStation external-id miss is treated as proof that postage was never bought',
    file: PROVIDER_ADAPTER,
    find: /    throw lookupUnavailable\(\r?\n      'ShipStation',\r?\n      replacementId,\r?\n      'external_shipment_not_found_without_no_effect_proof',\r?\n    \);/,
    replace: '    return null;',
    expect: 'a bare ShipStation lookup miss stays indeterminate without durable no-effect proof',
  },
  {
    id: 'M179',
    defect: 'two frozen duplicate-SKU items share one shipment-level ledger source identity',
    file: SHIPPED,
    find: '        sourceId: `${replacement.replacementShipmentId}:${item.id}`,',
    replace: '        sourceId: String(replacement.replacementShipmentId),',
    expect: 'duplicate-SKU items keep distinct ledger source identities',
  },
  {
    id: 'M180',
    defect: 'a NULL-client replacement falls back to the application-main key and can buy postage',
    file: CREDENTIAL_AUTHORITY,
    find: '  if (clientScope(input.requestedClientId) === null) return null;',
    replace: '',
    expect: 'a NULL replacement client selects NO provider credential authority',
  },
  {
    id: 'M181',
    defect: "the analysis scope helper stops excluding replacements, so every dashboard reader counts them",
    file: ANALYSIS,
    find: "  return sql`(${analysisShipmentScopeSelection(q)}) and s.source is distinct from 'replacement'`;",
    replace: "  return analysisShipmentScopeSelection(q);",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M182',
    defect: "a reader becomes unbound and merely GROUPS BY order_id, which is not a constraint",
    file: OUTBOX,
    find: "    FROM shipments WHERE id = ${shipmentId} LIMIT 1",
    replace: "    FROM shipments GROUP BY order_id, source LIMIT 1",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M183',
    defect: "one reader loses its exclusion while the same file keeps it in other statements",
    file: LABELS,
    find: "        .where(and(ordinaryShipmentSourcePredicate, eq(shipments.providerAccountId, providerAccountId)))",
    replace: "        .where(eq(shipments.providerAccountId, providerAccountId))",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M184',
    defect: "a bare ordinary read is added inside a replacement-owned file, inheriting its exemption",
    file: LIFECYCLE,
    find: "export async function enterReplacementReview(",
    replace: "export async function ps502BareReadProbe() {\n  return db.select({ id: shipments.id }).from(shipments).limit(1);\n}\n\nexport async function enterReplacementReview(",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M185',
    defect: "an acknowledged site is exchanged for a different unexcluded one while the count stays the same",
    file: SYNC,
    find: "    .select({ count: sql<number>`count(*)::int` })\n    .from(shipments);",
    replace: "    .select({ count: sql<number>`count(*)::int` })\n    .from(shipments)\n    .where(sql`true`);",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M186',
    defect: "a semicolon-free bare read is blessed by the exclusion in the NEXT statement",
    file: ADMIN,
    find: "        .innerJoin(orders, eq(orders.id, shipments.orderId))",
    replace: "        .innerJoin(orders, eq(orders.id, shipments.orderId))\n// eslint-disable-next-line\nconst ps502AsiProbe = db.select({ id: shipments.id }).from(shipments)",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M187',
    defect: "an unrelated table id is accepted as a shipments binding",
    file: ADMIN,
    find: "        .innerJoin(orders, eq(orders.id, shipments.orderId))",
    replace: "        .innerJoin(clients, eq(clients.id, shipments.clientId))",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M188',
    defect: "a predicate-shaped helper absorbs the following statement and passes as exclusion-carrying",
    file: ANALYSIS,
    find: "  return sql`(${analysisShipmentScopeSelection(q)}) and s.source is distinct from 'replacement'`;",
    replace: "  return analysisShipmentScopeSelection(q);\n}\nconst ps502MovedExclusion = sql`s.source is distinct from 'replacement'`;\nfunction ps502Unused(): SQL {",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
  {
    id: 'M190',
    defect: "an acknowledged site is changed only BEYOND its first 64 characters",
    file: LIFECYCLE_ORDER,
    find: "        input.shipmentId == null ? undefined : ne(shipments.id, input.shipmentId),\r",
    replace: "        input.shipmentId == null ? undefined : ne(shipments.id, input.shipmentId ?? 0),\r",
    expect: "every shipments READ SITE is excluded, replacement-owned, or acknowledged BY SITE",
  },
];

process.exit(runMutationMatrix({
  title: 'PS-502 mutation matrix',
  guard: 'scripts/ps-502-replacement-contract-guard.ts',
  mutations: MUTATIONS,
}));
